### PR TITLE
fix compilation error

### PR DESCRIPTION
**Pull request by llange**
Fix compilation error introduced in 2915281af0715a46de548f80a0104d4d9492e400 / #1032

### CODE REVIEW

**Comment by dexterbg** [comment]
Yes, fixed, thanks!
